---
- name: apt update
  become: yes
  action: apt update_cache=yes

- name: dev locale
  become: yes
  shell: update-locale LC_ALL=en_US.UTF-8

- name: set default locale
  become: yes
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: install packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - lynx
    - tmux
    - curl
    - checkinstall
    - aptitude
    - make
    - gcc
    - libjpeg8
    - libjpeg8-dev
    - python-imaging
    - python-pip
    - python-virtualenv
    - uwsgi
    - uwsgi-plugin-python
    - libpq-dev
    - libcurl4-openssl-dev
    - build-essential
