---
- name: apt update
  become: yes
  action: apt update_cache=yes

- name: dev locale
  become: yes
  shell: update-locale LC_ALL=en_US.UTF-8

- name: set default locale
  become: yes
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""

- name: install packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - lynx
    - tmux
    - curl
    - checkinstall
    - aptitude
    - make
    - gcc
    - libjpeg8
    - libjpeg8-dev
    - python-imaging
    - python-pip
    - python-virtualenv
    - libpq-dev
    - libcurl4-openssl-dev
    - build-essential

- name: add user
  become: yes
  user: name={{ username }} generate_ssh_key=yes shell=/bin/bash ssh_key_comment={{ username }}@{{ inventory_hostname }}

- name: create project directory
  become: yes
  file: path={{ project_dir }} state=directory group={{ username }} owner={{ username }}

- name: create logs directory
  become: yes
  file: path={{ project_dir }}/logs state=directory group={{ username }} owner={{ username }}

- name: clone project from repo
  become: true
  become_user: '{{ username }}'
  git:
    repo: '{{ repo }}'
    dest: '{{ project_homedir }}'
    accept_hostkey: true
  register: git

- name: copy local_settings.py
  become: true
  become_user: '{{ username }}'
  action: template src=config/{{ item }}.j2 dest={{ project_homedir }}/{{ project_slug }}/{{ item }} group={{ username }} owner={{ username }}
  with_items:
    - '{{ local_settings }}'
