---
- name: Install nginx
  become: yes
  apt: pkg=nginx-full state=latest

- name: ensures /var/log/nginx/ dir exists if not create
  become: yes
  file: path=/var/log/nginx/ state=directory group=www-data owner=www-data

- name: copy nginx config
  become: yes
  template: src=nginx.j2 dest=/etc/nginx/sites-available/{{ project_url }}

- name: create symlink nginx config
  become: yes
  file: src=/etc/nginx/sites-available/{{ project_url }} dest=/etc/nginx/sites-enabled/{{ project_url }} state=link

- name: remove /etc/nginx/sites-enabled/default
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: restart nginx
  become: yes
  service: name=nginx state=restarted
