---
- name: install webserver & DB / configuration
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
    - action: setup

  roles:
    - common
    - { role: postgresql, become: yes }
    - { role: virtualenv, become: yes }
    - application
    - uwsgi
    - supervisor
    - nginx
