# ansible-galaxy install -r requirements.yml
- src: git+https://github.com/ANXS/postgresql.git
  version: master
  name: postgresql

- src: git+https://github.com/cchurch/ansible-role-virtualenv.git
  version: master
  name: virtualenv
