---
- name: install packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - uwsgi
    - uwsgi-plugin-python

- name: copy uwsgi file
  become: yes
  template: src=uwsgi.j2 dest={{ project_homedir }}/uwsgi.{{ project_slug }}.ini group={{ username }} owner={{ username }}
